# Generated by Django 6.0 on 2025-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='file',
            new_name='report_file',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
